# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49eaafcffd53c423dad647ffb96e972a5c8ebe14005933974f72be30ac18bbd36b6b49f0aa0f594167a06ff45c5ee7d64646174e113f550512df10b3c80914b7

test:
  secret_key_base: b18fdc5c23e31e27e166ead11f4934de73a878768b9fbf606c7f940c2ae6d82200449cd55b26864a870443e4db45ab9c323ebc28feaff422264905e1ae7f4a60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
